local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.numberwidth = 3
opt.cursorline = true
opt.shiftwidth = 2
opt.signcolumn = "yes"
opt.guicursor = "i:block"
opt.breakindent = true
opt.undofile = true
opt.ignorecase = true
opt.smartcase = true
opt.updatetime = 250
opt.timeoutlen = 300
opt.splitright = true
opt.splitbelow = true
opt.list = false
opt.inccommand = "split"
opt.cursorline = true
opt.scrolloff = 10
opt.shiftround = true
opt.tabstop = 2
