local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.updatetime=300
opt.numberwidth = 3
opt.signcolumn = "yes"
opt.guicursor = "i:block"
opt.cursorline = false
opt.breakindent = true
opt.undofile = true
opt.ignorecase = true
opt.smartcase = true
opt.updatetime = 250
opt.timeoutlen = 300
opt.splitright = true
opt.splitbelow = true
opt.list = false
opt.inccommand = "split"
opt.scrolloff = 10
opt.shiftround = true
opt.clipboard = "unnamedplus"
opt.pumheight = 10

vim.opt.expandtab = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.smarttab = true
